import { DetailedWordBreakdown } from "../types";

export interface VerbMeta {
  infinitive: string;
  meaning: string;
  aux: "haben" | "sein";
  praeteritum?: string;
  partizip?: string;
  government?: string;
  isDativeVerb?: boolean;
}

export const PREPOSITION_DICT: Record<string, { case: "Dativ" | "Akkusativ" | "Genitiv" | "Zwei-Wege (Dativ/Akkusativ)"; meaning: string; note: string }> = {
  aus: { case: "Dativ", meaning: "out of / from", note: "Always requires Dativ. Indicates origin or material." },
  außer: { case: "Dativ", meaning: "except for / besides", note: "Always requires Dativ." },
  bei: { case: "Dativ", meaning: "at / with / near", note: "Always requires Dativ. Expresses location at a place or concurrent action." },
  mit: { case: "Dativ", meaning: "with / by means of", note: "Always requires Dativ. Expresses accompaniment or instrument." },
  nach: { case: "Dativ", meaning: "after / to (cities/countries)", note: "Always requires Dativ. Used for geographical destinations without articles or temporal sequence." },
  seit: { case: "Dativ", meaning: "since / for (time duration)", note: "Always requires Dativ. Describes an event continuing into present (uses German present tense)." },
  von: { case: "Dativ", meaning: "from / of", note: "Always requires Dativ. Expresses origin or possession." },
  zu: { case: "Dativ", meaning: "to / at", note: "Always requires Dativ. Expresses direction towards people, places, or idiomatic states ('zu Hause')." },
  gegenüber: { case: "Dativ", meaning: "opposite / towards", note: "Always requires Dativ." },

  durch: { case: "Akkusativ", meaning: "through / by means of", note: "Always requires Akkusativ. Indicates spatial transit or agency." },
  für: { case: "Akkusativ", meaning: "for", note: "Always requires Akkusativ. Expresses beneficiary, purpose, or duration." },
  gegen: { case: "Akkusativ", meaning: "against / around (time)", note: "Always requires Akkusativ." },
  ohne: { case: "Akkusativ", meaning: "without", note: "Always requires Akkusativ." },
  um: { case: "Akkusativ", meaning: "around / at (exact clock time)", note: "Always requires Akkusativ. Used for clock times ('um 8 Uhr') or encirclement." },
  bis: { case: "Akkusativ", meaning: "until / up to", note: "Always requires Akkusativ." },
  entlang: { case: "Akkusativ", meaning: "along", note: "Usually requires Akkusativ when placed after the noun." },

  wegen: { case: "Genitiv", meaning: "because of", note: "Standardly governs the Genitiv in formal German." },
  trotz: { case: "Genitiv", meaning: "in spite of / despite", note: "Requires the Genitiv in standard German." },
  während: { case: "Genitiv", meaning: "during", note: "Requires the Genitiv when used as a preposition ('während des Tages')." },
  aufgrund: { case: "Genitiv", meaning: "on the basis of / due to", note: "Prepositional compound governing the Genitiv." },
  infolge: { case: "Genitiv", meaning: "as a result of", note: "Formal Genitiv preposition." },
  statt: { case: "Genitiv", meaning: "instead of", note: "Requires the Genitiv." },

  an: { case: "Zwei-Wege (Dativ/Akkusativ)", meaning: "at / on (vertical border)", note: "Dativ for static location (Wo?), Akkusativ for direction (Wohin?)." },
  auf: { case: "Zwei-Wege (Dativ/Akkusativ)", meaning: "on (horizontal surface)", note: "Dativ for stationary location (Wo?), Akkusativ for motion onto (Wohin?)." },
  hinter: { case: "Zwei-Wege (Dativ/Akkusativ)", meaning: "behind", note: "Dativ for location (Wo?), Akkusativ for direction (Wohin?)." },
  in: { case: "Zwei-Wege (Dativ/Akkusativ)", meaning: "in / into", note: "Dativ for inside a location (Wo?), Akkusativ for movement into a space (Wohin?)." },
  neben: { case: "Zwei-Wege (Dativ/Akkusativ)", meaning: "next to / beside", note: "Dativ for location (Wo?), Akkusativ for direction (Wohin?)." },
  über: { case: "Zwei-Wege (Dativ/Akkusativ)", meaning: "over / above / about", note: "Dativ for position above; Akkusativ for motion across or topical preposition." },
  unter: { case: "Zwei-Wege (Dativ/Akkusativ)", meaning: "under / below / among", note: "Dativ for position under; Akkusativ for movement under." },
  vor: { case: "Zwei-Wege (Dativ/Akkusativ)", meaning: "in front of / ago (temporal)", note: "Dativ for spatial location or temporal 'ago'; Akkusativ for motion in front of." },
  zwischen: { case: "Zwei-Wege (Dativ/Akkusativ)", meaning: "between", note: "Dativ for location between two entities, Akkusativ for motion between." },
};

export const CONTRACTIONS_DICT: Record<string, { prep: string; article: string; case: string; meaning: string; explanation: string }> = {
  im: { prep: "in", article: "dem", case: "Dativ maskulin/neutral", meaning: "in the", explanation: "Contraction of 'in + dem'." },
  am: { prep: "an", article: "dem", case: "Dativ maskulin/neutral", meaning: "at the / on the", explanation: "Contraction of 'an + dem' (used with days, times of day like 'am Montag')." },
  zum: { prep: "zu", article: "dem", case: "Dativ maskulin/neutral", meaning: "to the", explanation: "Contraction of 'zu + dem' ('zu' always takes Dativ)." },
  zur: { prep: "zu", article: "der", case: "Dativ feminin", meaning: "to the", explanation: "Contraction of 'zu + der' (feminine dative after 'zu')." },
  beim: { prep: "bei", article: "dem", case: "Dativ maskulin/neutral", meaning: "at the / while doing", explanation: "Contraction of 'bei + dem' ('bei' always takes Dativ)." },
  vom: { prep: "von", article: "dem", case: "Dativ maskulin/neutral", meaning: "from the / of the", explanation: "Contraction of 'von + dem'." },
  ins: { prep: "in", article: "das", case: "Akkusativ neutral", meaning: "into the", explanation: "Contraction of 'in + das' (directional movement into a neuter space)." },
  ans: { prep: "an", article: "das", case: "Akkusativ neutral", meaning: "to / onto the", explanation: "Contraction of 'an + das'." },
  aufs: { prep: "auf", article: "das", case: "Akkusativ neutral", meaning: "onto the", explanation: "Contraction of 'auf + das'." },
  ums: { prep: "um", article: "das", case: "Akkusativ neutral", meaning: "around the", explanation: "Contraction of 'um + das'." },
};

export const SUBORDINATING_CONJUNCTIONS: Record<string, { meaning: string; clauseType: string; rule: string }> = {
  weil: { meaning: "because", clauseType: "Kausalsatz (causal clause)", rule: "Forces the conjugated finite verb to the very end of the subordinate clause." },
  da: { meaning: "since / because", clauseType: "Kausalsatz (known reason)", rule: "Introduces a known factual reason; sends verb to the clause end." },
  dass: { meaning: "that", clauseType: "Objektsatz / Inhaltssatz", rule: "Introduces indirect statement; finite verb goes to the clause end." },
  daß: { meaning: "that", clauseType: "Objektsatz", rule: "Traditional spelling of 'dass'; verb to the end." },
  obwohl: { meaning: "although / even though", clauseType: "Konzessivsatz (concessive)", rule: "Expresses contrast; sends the finite verb to the end." },
  obgleich: { meaning: "although", clauseType: "Konzessivsatz", rule: "Formal concessive conjunction; finite verb to the end." },
  wenn: { meaning: "if / whenever / when", clauseType: "Konditionalsatz / Temporalsatz", rule: "Sets condition or repeated event; finite verb goes to the end." },
  falls: { meaning: "in case / if", clauseType: "Konditionalsatz", rule: "Hypothetical condition; finite verb to the end." },
  nachdem: { meaning: "after", clauseType: "Temporalsatz (anteriority)", rule: "Temporal anteriority; verb goes to the end." },
  bevor: { meaning: "before", clauseType: "Temporalsatz (posteriority)", rule: "Subordinating temporal conjunction; finite verb to the end." },
  während: { meaning: "while / whereas", clauseType: "Temporalsatz / Adversativsatz", rule: "Simultaneous action or contrast; finite verb to the end." },
  solange: { meaning: "as long as", clauseType: "Temporalsatz (duration)", rule: "Subordinating temporal conjunction; finite verb to the end." },
  sobald: { meaning: "as soon as", clauseType: "Temporalsatz", rule: "Immediate sequence; finite verb to the end." },
  damit: { meaning: "so that / in order that", clauseType: "Finalsatz (purpose)", rule: "Expresses purpose; finite verb to the end." },
  sodass: { meaning: "so that (consequence)", clauseType: "Konsekutivsatz", rule: "Result clause; finite verb to the end." },
  ob: { meaning: "whether / if", clauseType: "Indirekter Fragesatz", rule: "Introduces yes/no indirect questions; finite verb to the end." },
  als: { meaning: "when (single past event)", clauseType: "Temporalsatz (unique past event)", rule: "Used for a single completed past event; finite verb to the end." },
};

export const COORDINATING_CONJUNCTIONS: Record<string, { meaning: string; rule: string }> = {
  und: { meaning: "and", rule: "Coordinating conjunction (Position 0). Does not change word order." },
  aber: { meaning: "but / however", rule: "Coordinating conjunction (Position 0). Connects clauses without shifting verb position." },
  oder: { meaning: "or", rule: "Coordinating conjunction (Position 0). Does not affect word order." },
  denn: { meaning: "for / because", rule: "Coordinating conjunction (Position 0). Expresses cause while keeping standard V2 main clause order." },
  sondern: { meaning: "but rather / instead", rule: "Coordinating conjunction (Position 0). Used after a negative clause ('nicht ..., sondern ...')." },
};

export const QUESTION_WORDS: Record<string, { meaning: string; role: string; explanation: string }> = {
  woher: { meaning: "from where / where from", role: "Interrogativadverb (Herkunft / Woher?)", explanation: "Asks about the origin or starting point of movement." },
  wohin: { meaning: "where to", role: "Interrogativadverb (Richtung / Wohin?)", explanation: "Asks about the destination or direction of movement." },
  wo: { meaning: "where", role: "Interrogativadverb (Ort / Wo?)", explanation: "Asks about stationary location." },
  wann: { meaning: "when", role: "Interrogativadverb (Zeit)", explanation: "Asks about time or date." },
  warum: { meaning: "why", role: "Interrogativadverb (Grund)", explanation: "Asks about reason or cause." },
  wieso: { meaning: "why / how come", role: "Interrogativadverb (Grund)", explanation: "Informal synonym of warum." },
  weshalb: { meaning: "why / wherefore", role: "Interrogativadverb (Grund)", explanation: "Formal interrogative adverb asking for reasons." },
  wie: { meaning: "how / what (in names)", role: "Interrogativadverb (Art und Weise)", explanation: "Asks about manner, condition, or identity ('Wie heißen Sie?')." },
  wieviel: { meaning: "how much", role: "Interrogativpronomen (Menge)", explanation: "Asks about quantity or price." },
  "wie viel": { meaning: "how much", role: "Interrogativpronomen (Menge)", explanation: "Asks about quantity or price." },
  "wie viele": { meaning: "how many", role: "Interrogativpronomen (Anzahl)", explanation: "Asks about countable quantity." },
  wer: { meaning: "who (subject)", role: "Interrogativpronomen (Nominativ)", explanation: "Asks for the grammatical subject of the sentence." },
  wen: { meaning: "whom / who (direct object)", role: "Interrogativpronomen (Akkusativ)", explanation: "Asks for the direct accusative object." },
  wem: { meaning: "to whom (indirect object)", role: "Interrogativpronomen (Dativ)", explanation: "Asks for the indirect dative object." },
  wessen: { meaning: "whose", role: "Interrogativpronomen (Genitiv)", explanation: "Asks for possession." },
  was: { meaning: "what", role: "Interrogativpronomen (Sache)", explanation: "Asks about things, actions, or concepts." },
  welcher: { meaning: "which (masculine)", role: "Interrogativartikel / Pronomen", explanation: "Selects a specific item from a group." },
  welche: { meaning: "which (feminine / plural)", role: "Interrogativartikel / Pronomen", explanation: "Selects a specific item from a group." },
  welches: { meaning: "which (neuter)", role: "Interrogativartikel / Pronomen", explanation: "Selects a specific item from a group." },
  welchen: { meaning: "which (accusative masculine)", role: "Interrogativartikel / Pronomen", explanation: "Selects a specific masculine object." },
  welchem: { meaning: "which (dative)", role: "Interrogativartikel / Pronomen", explanation: "Selects a dative entity." },
};

export const PRONOUNS_DICT: Record<string, { meaning: string; pos: string; role: string; morph: string }> = {
  ich: { meaning: "I", pos: "Personalpronomen", role: "Subjekt (Nominativ)", morph: "1. Person Singular, Nominativ" },
  du: { meaning: "you (informal singular)", pos: "Personalpronomen", role: "Subjekt (Nominativ)", morph: "2. Person Singular, Nominativ" },
  er: { meaning: "he", pos: "Personalpronomen", role: "Subjekt (Nominativ)", morph: "3. Person Singular maskulin, Nominativ" },
  sie: { meaning: "she / they", pos: "Personalpronomen", role: "Subjekt oder Akkusativ", morph: "3. Person feminin / Plural" },
  es: { meaning: "it", pos: "Personalpronomen", role: "Subjekt oder Akkusativ (neutral)", morph: "3. Person Singular neutral" },
  wir: { meaning: "we", pos: "Personalpronomen", role: "Subjekt (Nominativ)", morph: "1. Person Plural, Nominativ" },
  ihr: { meaning: "you (informal plural) / her", pos: "Personalpronomen", role: "Subjekt / Dativ / Possessiv", morph: "2. Person Plural / Dativ feminin" },
  Sie: { meaning: "you (formal)", pos: "Höflichkeitspronomen", role: "Subjekt oder Akkusativ (formell)", morph: "Höflichkeitsform (immer großgeschrieben)" },
  
  mich: { meaning: "me", pos: "Personalpronomen", role: "Akkusativobjekt / Reflexiv", morph: "1. Person Singular, Akkusativ" },
  dich: { meaning: "you", pos: "Personalpronomen", role: "Akkusativobjekt / Reflexiv", morph: "2. Person Singular, Akkusativ" },
  ihn: { meaning: "him", pos: "Personalpronomen", role: "Akkusativobjekt", morph: "3. Person Singular maskulin, Akkusativ" },
  uns: { meaning: "us", pos: "Personalpronomen", role: "Akkusativ- / Dativobjekt", morph: "1. Person Plural" },
  euch: { meaning: "you (plural)", pos: "Personalpronomen", role: "Akkusativ- / Dativobjekt", morph: "2. Person Plural" },
  sich: { meaning: "oneself / himself / herself / themselves", pos: "Reflexivpronomen", role: "Reflexivpronomen", morph: "3. Person (Dativ/Akkusativ)" },

  mir: { meaning: "to me / me", pos: "Personalpronomen", role: "Dativobjekt", morph: "1. Person Singular, Dativ" },
  dir: { meaning: "to you / you", pos: "Personalpronomen", role: "Dativobjekt", morph: "2. Person Singular, Dativ" },
  ihm: { meaning: "to him / it", pos: "Personalpronomen", role: "Dativobjekt", morph: "3. Person Singular maskulin/neutral, Dativ" },
  ihnen: { meaning: "to them", pos: "Personalpronomen", role: "Dativobjekt", morph: "3. Person Plural, Dativ" },
  Ihnen: { meaning: "to you (formal)", pos: "Höflichkeitspronomen", role: "Dativobjekt (formell)", morph: "Höflichkeitsform Dativ (immer großgeschrieben)" },

  mein: { meaning: "my", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin/neutral Nominativ" },
  meine: { meaning: "my", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "feminin / Plural" },
  meinen: { meaning: "my", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin Akkusativ / Dativ Plural" },
  meinem: { meaning: "my", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin/neutral Dativ" },
  meiner: { meaning: "my", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "feminin Dativ/Genitiv" },
  meines: { meaning: "my", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin/neutral Genitiv" },

  dein: { meaning: "your", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "2. Person Singular" },
  deine: { meaning: "your", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "feminin / Plural" },
  deinen: { meaning: "your", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin Akkusativ" },
  deinem: { meaning: "your", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin/neutral Dativ" },
  deiner: { meaning: "your", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "feminin Dativ" },

  sein: { meaning: "his / its", pos: "Possessivartikel / Verb", role: "Possessivbegleiter oder Kopula", morph: "Grundform" },
  seine: { meaning: "his / its", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "feminin / Plural" },
  seinen: { meaning: "his / its", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin Akkusativ" },
  seinem: { meaning: "his / its", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin/neutral Dativ" },

  ihre: { meaning: "her / their / your (formal)", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "feminin / Plural" },
  ihren: { meaning: "her / their / your (formal)", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin Akkusativ / Dativ Plural" },
  ihrem: { meaning: "her / their / your (formal)", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin/neutral Dativ" },

  unser: { meaning: "our", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "1. Person Plural" },
  unsere: { meaning: "our", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "feminin / Plural" },
  unseren: { meaning: "our", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin Akkusativ" },
  unserem: { meaning: "our", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin/neutral Dativ" },

  euer: { meaning: "your (plural)", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "2. Person Plural" },
  eure: { meaning: "your (plural)", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "feminin / Plural" },
  euren: { meaning: "your (plural)", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin Akkusativ" },
  eurem: { meaning: "your (plural)", pos: "Possessivartikel", role: "Possessivbegleiter", morph: "maskulin/neutral Dativ" },

  Ihr: { meaning: "your (formal)", pos: "Höflichkeits-Possessiv", role: "Possessivbegleiter (formell)", morph: "Höflichkeitsform" },
  Ihre: { meaning: "your (formal)", pos: "Höflichkeits-Possessiv", role: "Possessivbegleiter (formell)", morph: "Höflichkeitsform feminin/Plural" },
  Ihren: { meaning: "your (formal)", pos: "Höflichkeits-Possessiv", role: "Possessivbegleiter (formell)", morph: "maskulin Akkusativ formell" },
  Ihrem: { meaning: "your (formal)", pos: "Höflichkeits-Possessiv", role: "Possessivbegleiter (formell)", morph: "maskulin/neutral Dativ formell" },
};

export const COMMON_VERBS: Record<string, VerbMeta> = {
  // Sein
  ist: { infinitive: "sein", meaning: "is", aux: "sein", praeteritum: "war", partizip: "gewesen", government: "Nominativ (Kopulaverb)" },
  sind: { infinitive: "sein", meaning: "are", aux: "sein", praeteritum: "waren", partizip: "gewesen", government: "Nominativ (Kopulaverb)" },
  bin: { infinitive: "sein", meaning: "am", aux: "sein", praeteritum: "war", partizip: "gewesen", government: "Nominativ (Kopulaverb)" },
  bist: { infinitive: "sein", meaning: "are (informal singular)", aux: "sein", praeteritum: "war", partizip: "gewesen", government: "Nominativ" },
  seid: { infinitive: "sein", meaning: "are (informal plural)", aux: "sein", praeteritum: "war", partizip: "gewesen", government: "Nominativ" },
  war: { infinitive: "sein", meaning: "was", aux: "sein", praeteritum: "war", partizip: "gewesen", government: "Präteritum von sein" },
  waren: { infinitive: "sein", meaning: "were", aux: "sein", praeteritum: "waren", partizip: "gewesen", government: "Präteritum von sein" },
  wäre: { infinitive: "sein", meaning: "would be", aux: "sein", praeteritum: "war", partizip: "gewesen", government: "Konjunktiv II von sein" },
  wären: { infinitive: "sein", meaning: "would be (plural)", aux: "sein", praeteritum: "waren", partizip: "gewesen", government: "Konjunktiv II von sein" },
  gewesen: { infinitive: "sein", meaning: "been", aux: "sein", partizip: "gewesen", government: "Partizip II von sein" },

  // Haben
  hat: { infinitive: "haben", meaning: "has", aux: "haben", praeteritum: "hatte", partizip: "gehabt", government: "Akkusativ" },
  habe: { infinitive: "haben", meaning: "have (1st person)", aux: "haben", praeteritum: "hatte", partizip: "gehabt", government: "Akkusativ" },
  hast: { infinitive: "haben", meaning: "have (2nd person)", aux: "haben", praeteritum: "hattest", partizip: "gehabt", government: "Akkusativ" },
  haben: { infinitive: "haben", meaning: "have", aux: "haben", praeteritum: "hatten", partizip: "gehabt", government: "Akkusativ" },
  habt: { infinitive: "haben", meaning: "have (plural)", aux: "haben", praeteritum: "hattet", partizip: "gehabt", government: "Akkusativ" },
  hatte: { infinitive: "haben", meaning: "had", aux: "haben", praeteritum: "hatte", partizip: "gehabt", government: "Präteritum von haben" },
  hatten: { infinitive: "haben", meaning: "had (plural)", aux: "haben", praeteritum: "hatten", partizip: "gehabt", government: "Präteritum von haben" },
  hätte: { infinitive: "haben", meaning: "would have", aux: "haben", praeteritum: "hatte", partizip: "gehabt", government: "Konjunktiv II von haben" },
  hätten: { infinitive: "haben", meaning: "would have (plural)", aux: "haben", praeteritum: "hatten", partizip: "gehabt", government: "Konjunktiv II von haben" },
  gehabt: { infinitive: "haben", meaning: "had (participle)", aux: "haben", partizip: "gehabt", government: "Partizip II von haben" },

  // Werden
  wird: { infinitive: "werden", meaning: "becomes / will / is (passive auxiliary)", aux: "sein", praeteritum: "wurde", partizip: "geworden", government: "Nominativ / Passiv / Futur" },
  werden: { infinitive: "werden", meaning: "become / will / are (passive)", aux: "sein", praeteritum: "wurden", partizip: "geworden", government: "Passivhilfsverb / Futur" },
  wurde: { infinitive: "werden", meaning: "became / was (passive)", aux: "sein", praeteritum: "wurde", partizip: "geworden", government: "Präteritum Passiv" },
  wurden: { infinitive: "werden", meaning: "were (passive plural)", aux: "sein", praeteritum: "wurden", partizip: "geworden", government: "Präteritum Passiv" },
  würde: { infinitive: "werden", meaning: "would", aux: "sein", praeteritum: "wurde", partizip: "geworden", government: "Konjunktiv II Hilfsverb" },
  würden: { infinitive: "werden", meaning: "would (plural)", aux: "sein", praeteritum: "wurden", partizip: "geworden", government: "Konjunktiv II Hilfsverb" },
  worden: { infinitive: "werden", meaning: "been (passive participle)", aux: "sein", partizip: "worden", government: "Passiv Partizip II" },
  geworden: { infinitive: "werden", meaning: "become (participle)", aux: "sein", partizip: "geworden", government: "Partizip II von werden" },

  // Kommen
  komme: { infinitive: "kommen", meaning: "come (1st person)", aux: "sein", praeteritum: "kam", partizip: "gekommen", government: "aus + Dativ" },
  kommst: { infinitive: "kommen", meaning: "come (2nd person)", aux: "sein", praeteritum: "kamst", partizip: "gekommen", government: "aus + Dativ" },
  kommt: { infinitive: "kommen", meaning: "comes", aux: "sein", praeteritum: "kam", partizip: "gekommen", government: "aus + Dativ / nach + Dativ" },
  kommen: { infinitive: "kommen", meaning: "come", aux: "sein", praeteritum: "kamen", partizip: "gekommen", government: "aus + Dativ (Perfekt mit sein)" },
  kam: { infinitive: "kommen", meaning: "came", aux: "sein", praeteritum: "kam", partizip: "gekommen", government: "Präteritum von kommen" },
  kamen: { infinitive: "kommen", meaning: "came (plural)", aux: "sein", praeteritum: "kamen", partizip: "gekommen", government: "Präteritum von kommen" },
  gekommen: { infinitive: "kommen", meaning: "come (participle)", aux: "sein", partizip: "gekommen", government: "Partizip II mit sein" },

  // Heißen
  heiße: { infinitive: "heißen", meaning: "am called / am named", aux: "haben", praeteritum: "hieß", partizip: "geheißen", government: "Gleichsetzungsnominativ" },
  heißt: { infinitive: "heißen", meaning: "is called / means", aux: "haben", praeteritum: "hieß", partizip: "geheißen", government: "Gleichsetzungsnominativ" },
  heißen: { infinitive: "heißen", meaning: "are called / to be called", aux: "haben", praeteritum: "hießen", partizip: "geheißen", government: "Gleichsetzungsnominativ" },

  // Modals
  kann: { infinitive: "können", meaning: "can / is able to", aux: "haben", praeteritum: "konnte", partizip: "gekonnt", government: "Modalverb (+ Infinitiv)" },
  kannst: { infinitive: "können", meaning: "can (informal singular)", aux: "haben", praeteritum: "konntest", partizip: "gekonnt", government: "Modalverb (+ Infinitiv)" },
  können: { infinitive: "können", meaning: "can / to be able to", aux: "haben", praeteritum: "konnten", partizip: "gekonnt", government: "Modalverb (+ Infinitiv)" },
  könnte: { infinitive: "können", meaning: "could / might", aux: "haben", praeteritum: "konnte", partizip: "gekonnt", government: "Konjunktiv II von können" },
  könnten: { infinitive: "können", meaning: "could / might (plural)", aux: "haben", praeteritum: "konnten", partizip: "gekonnt", government: "Konjunktiv II von können" },
  konnte: { infinitive: "können", meaning: "could / was able to", aux: "haben", praeteritum: "konnte", partizip: "gekonnt", government: "Präteritum von können" },

  muss: { infinitive: "müssen", meaning: "must / has to", aux: "haben", praeteritum: "musste", partizip: "gemusst", government: "Modalverb (+ Infinitiv)" },
  musst: { infinitive: "müssen", meaning: "must (informal singular)", aux: "haben", praeteritum: "musstest", partizip: "gemusst", government: "Modalverb (+ Infinitiv)" },
  müssen: { infinitive: "müssen", meaning: "must / have to", aux: "haben", praeteritum: "mussten", partizip: "gemusst", government: "Modalverb (+ Infinitiv)" },
  müsste: { infinitive: "müssen", meaning: "should / would have to", aux: "haben", praeteritum: "musste", partizip: "gemusst", government: "Konjunktiv II von müssen" },
  musste: { infinitive: "müssen", meaning: "had to", aux: "haben", praeteritum: "musste", partizip: "gemusst", government: "Präteritum von müssen" },

  will: { infinitive: "wollen", meaning: "wants to / intends to", aux: "haben", praeteritum: "wollte", partizip: "gewollt", government: "Modalverb (+ Infinitiv)" },
  willst: { infinitive: "wollen", meaning: "want to (informal singular)", aux: "haben", praeteritum: "wolltest", partizip: "gewollt", government: "Modalverb (+ Infinitiv)" },
  wollen: { infinitive: "wollen", meaning: "want to / to intend", aux: "haben", praeteritum: "wollten", partizip: "gewollt", government: "Modalverb (+ Infinitiv)" },
  wollte: { infinitive: "wollen", meaning: "wanted to", aux: "haben", praeteritum: "wollte", partizip: "gewollt", government: "Präteritum von wollen" },

  soll: { infinitive: "sollen", meaning: "should / is supposed to", aux: "haben", praeteritum: "sollte", partizip: "gesollt", government: "Modalverb (duty / expectation)" },
  sollst: { infinitive: "sollen", meaning: "should (informal singular)", aux: "haben", praeteritum: "solltest", partizip: "gesollt", government: "Modalverb" },
  sollen: { infinitive: "sollen", meaning: "should / to be supposed to", aux: "haben", praeteritum: "sollten", partizip: "gesollt", government: "Modalverb" },
  sollte: { infinitive: "sollen", meaning: "should (advice / condition)", aux: "haben", praeteritum: "sollte", partizip: "gesollt", government: "Konjunktiv II / Präteritum" },

  darf: { infinitive: "dürfen", meaning: "may / is allowed to", aux: "haben", praeteritum: "durfte", partizip: "gedurft", government: "Modalverb (permission)" },
  darfst: { infinitive: "dürfen", meaning: "may (informal singular)", aux: "haben", praeteritum: "durftest", partizip: "gedurft", government: "Modalverb" },
  dürfen: { infinitive: "dürfen", meaning: "may / to be allowed to", aux: "haben", praeteritum: "durften", partizip: "gedurft", government: "Modalverb" },
  durfte: { infinitive: "dürfen", meaning: "was allowed to", aux: "haben", praeteritum: "durfte", partizip: "gedurft", government: "Präteritum von dürfen" },

  möchte: { infinitive: "mögen", meaning: "would like to", aux: "haben", praeteritum: "mochte", partizip: "gemocht", government: "Höflicher Wunsch (+ Infinitiv/Akkusativ)" },
  möchtest: { infinitive: "mögen", meaning: "would like to (informal)", aux: "haben", praeteritum: "mochtest", partizip: "gemocht", government: "Höflicher Wunsch" },
  möchten: { infinitive: "mögen", meaning: "would like to (plural)", aux: "haben", praeteritum: "mochten", partizip: "gemocht", government: "Höflicher Wunsch" },

  // Dative governing verbs
  hilft: { infinitive: "helfen", meaning: "helps", aux: "haben", praeteritum: "half", partizip: "geholfen", government: "Dativ (helfen + jdm.)", isDativeVerb: true },
  helfe: { infinitive: "helfen", meaning: "help (1st person)", aux: "haben", praeteritum: "half", partizip: "geholfen", government: "Dativ", isDativeVerb: true },
  helfen: { infinitive: "helfen", meaning: "to help", aux: "haben", praeteritum: "halfen", partizip: "geholfen", government: "Dativ (always takes Dativ object)", isDativeVerb: true },
  geholfen: { infinitive: "helfen", meaning: "helped", aux: "haben", praeteritum: "half", partizip: "geholfen", government: "Dativ (Partizip II)", isDativeVerb: true },

  dankt: { infinitive: "danken", meaning: "thanks", aux: "haben", praeteritum: "dankte", partizip: "gedankt", government: "Dativ (jdm. danken)", isDativeVerb: true },
  danke: { infinitive: "danken", meaning: "thank (1st person) / thanks", aux: "haben", praeteritum: "dankte", partizip: "gedankt", government: "Dativ", isDativeVerb: true },

  gehört: { infinitive: "gehören", meaning: "belongs to", aux: "haben", praeteritum: "gehörte", partizip: "gehört", government: "Dativ (jdm. gehören)", isDativeVerb: true },
  gefällt: { infinitive: "gefallen", meaning: "pleases / appeals to", aux: "haben", praeteritum: "gefiel", partizip: "gefallen", government: "Dativ (jdm. gefallen)", isDativeVerb: true },
  schmeckt: { infinitive: "schmecken", meaning: "tastes good to", aux: "haben", praeteritum: "schmeckte", partizip: "geschmeckt", government: "Dativ (jdm. schmecken)", isDativeVerb: true },
  passt: { infinitive: "passen", meaning: "fits / suits", aux: "haben", praeteritum: "passte", partizip: "gepasst", government: "Dativ (jdm. passen)", isDativeVerb: true },

  // Everyday actions
  geht: { infinitive: "gehen", meaning: "goes / walks", aux: "sein", praeteritum: "ging", partizip: "gegangen", government: "Perfekt mit sein" },
  gehe: { infinitive: "gehen", meaning: "go / walk (1st person)", aux: "sein", praeteritum: "ging", partizip: "gegangen", government: "Perfekt mit sein" },
  ging: { infinitive: "gehen", meaning: "went", aux: "sein", praeteritum: "ging", partizip: "gegangen", government: "Präteritum von gehen" },
  gegangen: { infinitive: "gehen", meaning: "gone / walked", aux: "sein", partizip: "gegangen", government: "Partizip II mit sein" },

  macht: { infinitive: "machen", meaning: "makes / does", aux: "haben", praeteritum: "machte", partizip: "gemacht", government: "Akkusativ" },
  mache: { infinitive: "machen", meaning: "make / do (1st person)", aux: "haben", praeteritum: "machte", partizip: "gemacht", government: "Akkusativ" },
  machen: { infinitive: "machen", meaning: "make / do", aux: "haben", praeteritum: "machten", partizip: "gemacht", government: "Akkusativ" },
  gemacht: { infinitive: "machen", meaning: "made / done", aux: "haben", partizip: "gemacht", government: "Partizip II" },

  trinkt: { infinitive: "trinken", meaning: "drinks", aux: "haben", praeteritum: "trank", partizip: "getrunken", government: "Akkusativ" },
  trinke: { infinitive: "trinken", meaning: "drink (1st person)", aux: "haben", praeteritum: "trank", partizip: "getrunken", government: "Akkusativ" },
  trinken: { infinitive: "trinken", meaning: "drink / to drink", aux: "haben", praeteritum: "tranken", partizip: "getrunken", government: "Akkusativ" },
  getrunken: { infinitive: "trinken", meaning: "drunk / drank (participle)", aux: "haben", partizip: "getrunken", government: "Partizip II" },

  isst: { infinitive: "essen", meaning: "eats", aux: "haben", praeteritum: "aß", partizip: "gegessen", government: "Akkusativ" },
  esse: { infinitive: "essen", meaning: "eat (1st person)", aux: "haben", praeteritum: "aß", partizip: "gegessen", government: "Akkusativ" },
  essen: { infinitive: "essen", meaning: "eat / food", aux: "haben", praeteritum: "aßen", partizip: "gegessen", government: "Akkusativ" },
  gegessen: { infinitive: "essen", meaning: "eaten", aux: "haben", partizip: "gegessen", government: "Partizip II" },

  wohnt: { infinitive: "wohnen", meaning: "lives / resides", aux: "haben", praeteritum: "wohnte", partizip: "gewohnt", government: "in + Dativ" },
  wohne: { infinitive: "wohnen", meaning: "live / reside (1st person)", aux: "haben", praeteritum: "wohnte", partizip: "gewohnt", government: "in + Dativ" },
  wohnen: { infinitive: "wohnen", meaning: "live / to reside", aux: "haben", praeteritum: "wohnten", partizip: "gewohnt", government: "in + Dativ" },

  arbeitet: { infinitive: "arbeiten", meaning: "works", aux: "haben", praeteritum: "arbeitete", partizip: "gearbeitet", government: "bei / an + Dativ" },
  arbeite: { infinitive: "arbeiten", meaning: "work (1st person)", aux: "haben", praeteritum: "arbeitete", partizip: "gearbeitet", government: "bei + Dativ" },
  arbeiten: { infinitive: "arbeiten", meaning: "work / to work", aux: "haben", praeteritum: "arbeiteten", partizip: "gearbeitet", government: "bei + Dativ" },

  lernt: { infinitive: "lernen", meaning: "learns / studies", aux: "haben", praeteritum: "lernte", partizip: "gelernt", government: "Akkusativ" },
  lerne: { infinitive: "lernen", meaning: "learn / study (1st person)", aux: "haben", praeteritum: "lernte", partizip: "gelernt", government: "Akkusativ" },
  lernen: { infinitive: "lernen", meaning: "learn / to study", aux: "haben", praeteritum: "lernten", partizip: "gelernt", government: "Akkusativ" },

  spricht: { infinitive: "sprechen", meaning: "speaks", aux: "haben", praeteritum: "sprach", partizip: "gesprochen", government: "Akkusativ / über + Akkusativ" },
  spreche: { infinitive: "sprechen", meaning: "speak (1st person)", aux: "haben", praeteritum: "sprach", partizip: "gesprochen", government: "Akkusativ" },
  sprechen: { infinitive: "sprechen", meaning: "speak / to speak", aux: "haben", praeteritum: "sprachen", partizip: "gesprochen", government: "Akkusativ" },

  sieht: { infinitive: "sehen", meaning: "sees", aux: "haben", praeteritum: "sah", partizip: "gesehen", government: "Akkusativ" },
  sehe: { infinitive: "sehen", meaning: "see (1st person)", aux: "haben", praeteritum: "sah", partizip: "gesehen", government: "Akkusativ" },
  sehen: { infinitive: "sehen", meaning: "see / to see", aux: "haben", praeteritum: "sahen", partizip: "gesehen", government: "Akkusativ" },
  gesehen: { infinitive: "sehen", meaning: "seen", aux: "haben", partizip: "gesehen", government: "Partizip II" },

  schläft: { infinitive: "schlafen", meaning: "sleeps", aux: "haben", praeteritum: "schlief", partizip: "geschlafen", government: "intransitiv" },
  schlafe: { infinitive: "schlafen", meaning: "sleep (1st person)", aux: "haben", praeteritum: "schlief", partizip: "geschlafen", government: "intransitiv" },

  fährt: { infinitive: "fahren", meaning: "drives / travels", aux: "sein", praeteritum: "fuhr", partizip: "gefahren", government: "Perfekt mit sein" },
  fahre: { infinitive: "fahren", meaning: "drive / travel (1st person)", aux: "sein", praeteritum: "fuhr", partizip: "gefahren", government: "Perfekt mit sein" },
  fahren: { infinitive: "fahren", meaning: "drive / travel", aux: "sein", praeteritum: "fuhren", partizip: "gefahren", government: "Perfekt mit sein" },
  gefahren: { infinitive: "fahren", meaning: "driven / travelled", aux: "sein", partizip: "gefahren", government: "Partizip II mit sein" },

  bleibt: { infinitive: "bleiben", meaning: "stays / remains", aux: "sein", praeteritum: "blieb", partizip: "geblieben", government: "Perfekt mit sein" },
  bleiben: { infinitive: "bleiben", meaning: "stay / remain", aux: "sein", praeteritum: "blieben", partizip: "geblieben", government: "Perfekt mit sein" },
  geblieben: { infinitive: "bleiben", meaning: "stayed", aux: "sein", partizip: "geblieben", government: "Partizip II mit sein" },

  trifft: { infinitive: "treffen", meaning: "meets / hits", aux: "haben", praeteritum: "traf", partizip: "getroffen", government: "Akkusativ / eine Entscheidung treffen" },
  treffen: { infinitive: "treffen", meaning: "meet / to make", aux: "haben", praeteritum: "trafen", partizip: "getroffen", government: "Akkusativ" },
  getroffen: { infinitive: "treffen", meaning: "met / hit", aux: "haben", partizip: "getroffen", government: "Partizip II" },

  nimmt: { infinitive: "nehmen", meaning: "takes", aux: "haben", praeteritum: "nahm", partizip: "genommen", government: "Akkusativ" },
  nehmen: { infinitive: "nehmen", meaning: "take / to take", aux: "haben", praeteritum: "nahmen", partizip: "genommen", government: "Akkusativ" },
  genommen: { infinitive: "nehmen", meaning: "taken", aux: "haben", partizip: "genommen", government: "Partizip II" },

  gibt: { infinitive: "geben", meaning: "gives / there is ('es gibt')", aux: "haben", praeteritum: "gab", partizip: "gegeben", government: "es gibt + Akkusativ" },
  gab: { infinitive: "geben", meaning: "gave / there was", aux: "haben", praeteritum: "gab", partizip: "gegeben", government: "Präteritum von geben" },
  gegeben: { infinitive: "geben", meaning: "given", aux: "haben", partizip: "gegeben", government: "Partizip II" },

  weiß: { infinitive: "wissen", meaning: "knows (facts)", aux: "haben", praeteritum: "wusste", partizip: "gewusst", government: "Präteritopräsens" },
  weißt: { infinitive: "wissen", meaning: "know (2nd person)", aux: "haben", praeteritum: "wusstest", partizip: "gewusst", government: "Präteritopräsens" },
  wissen: { infinitive: "wissen", meaning: "know (facts)", aux: "haben", praeteritum: "wussten", partizip: "gewusst", government: "Akkusativ / Nebensatz" },

  kennt: { infinitive: "kennen", meaning: "knows / is familiar with", aux: "haben", praeteritum: "kannte", partizip: "gekannt", government: "Akkusativ (Personen/Orte)" },
  kenne: { infinitive: "kennen", meaning: "know / am familiar with (1st person)", aux: "haben", praeteritum: "kannte", partizip: "gekannt", government: "Akkusativ" },
  kennen: { infinitive: "kennen", meaning: "know / to be familiar with", aux: "haben", praeteritum: "kannten", partizip: "gekannt", government: "Akkusativ" },

  denkt: { infinitive: "denken", meaning: "thinks", aux: "haben", praeteritum: "dachte", partizip: "gedacht", government: "an + Akkusativ" },
  denke: { infinitive: "denken", meaning: "think (1st person)", aux: "haben", praeteritum: "dachte", partizip: "gedacht", government: "an + Akkusativ" },

  findet: { infinitive: "finden", meaning: "finds / deems", aux: "haben", praeteritum: "fand", partizip: "gefunden", government: "Akkusativ" },
  finde: { infinitive: "finden", meaning: "find (1st person)", aux: "haben", praeteritum: "fand", partizip: "gefunden", government: "Akkusativ" },
  gefunden: { infinitive: "finden", meaning: "found", aux: "haben", partizip: "gefunden", government: "Partizip II" },

  steht: { infinitive: "stehen", meaning: "stands / is located", aux: "haben", praeteritum: "stand", partizip: "gestanden", government: "in/auf + Dativ" },
  stand: { infinitive: "stehen", meaning: "stood", aux: "haben", praeteritum: "stand", partizip: "gestanden", government: "Präteritum" },
  gestanden: { infinitive: "stehen", meaning: "stood", aux: "haben", partizip: "gestanden", government: "Partizip II" },

  liegt: { infinitive: "liegen", meaning: "lies / is located horizontally", aux: "haben", praeteritum: "lag", partizip: "gelegen", government: "in/auf + Dativ" },
  sitzt: { infinitive: "sitzen", meaning: "sits", aux: "haben", praeteritum: "saß", partizip: "gesessen", government: "auf/in + Dativ" },

  bringt: { infinitive: "bringen", meaning: "brings", aux: "haben", praeteritum: "brachte", partizip: "gebracht", government: "Akkusativ" },
  gebracht: { infinitive: "bringen", meaning: "brought", aux: "haben", partizip: "gebracht", government: "Partizip II" },

  sagt: { infinitive: "sagen", meaning: "says / tells", aux: "haben", praeteritum: "sagte", partizip: "gesagt", government: "Akkusativ / Dativ" },
  sage: { infinitive: "sagen", meaning: "say (1st person)", aux: "haben", praeteritum: "sagte", partizip: "gesagt", government: "Akkusativ" },
  gesagt: { infinitive: "sagen", meaning: "said", aux: "haben", partizip: "gesagt", government: "Partizip II" },

  fragt: { infinitive: "fragen", meaning: "asks", aux: "haben", praeteritum: "fragte", partizip: "gefragt", government: "Akkusativ" },
  antwortet: { infinitive: "antworten", meaning: "answers", aux: "haben", praeteritum: "antwortete", partizip: "geantwortet", government: "auf + Akkusativ / Dativ" },
  braucht: { infinitive: "brauchen", meaning: "needs", aux: "haben", praeteritum: "brauchte", partizip: "gebraucht", government: "Akkusativ" },
  sucht: { infinitive: "suchen", meaning: "searches for / seeks", aux: "haben", praeteritum: "suchte", partizip: "gesucht", government: "Akkusativ" },
  versteht: { infinitive: "verstehen", meaning: "understands", aux: "haben", praeteritum: "verstand", partizip: "verstanden", government: "Akkusativ" },
  verstanden: { infinitive: "verstehen", meaning: "understood", aux: "haben", partizip: "verstanden", government: "Partizip II" },
  regnet: { infinitive: "regnen", meaning: "rains", aux: "haben", praeteritum: "regnete", partizip: "geregnet", government: "impersonales Verb ('es regnet')" },
  regnete: { infinitive: "regnen", meaning: "rained", aux: "haben", praeteritum: "regnete", partizip: "geregnet", government: "Präteritum" },
};

export const COMMON_NOUNS: Record<string, { meaning: string; gender: "maskulin" | "feminin" | "neutral"; plural?: string }> = {
  // Common people & titles
  herr: { meaning: "Mr. / gentleman / sir", gender: "maskulin", plural: "Herren" },
  frau: { meaning: "Mrs. / Ms. / woman / wife", gender: "feminin", plural: "Frauen" },
  dr: { meaning: "Doctor", gender: "maskulin" },
  doktor: { meaning: "Doctor", gender: "maskulin" },
  name: { meaning: "name", gender: "maskulin", plural: "Namen" },
  namen: { meaning: "names / name (inflected)", gender: "maskulin", plural: "Namen" },
  kind: { meaning: "child", gender: "neutral", plural: "Kinder" },
  kinder: { meaning: "children", gender: "neutral", plural: "Kinder" },
  sohn: { meaning: "son", gender: "maskulin", plural: "Söhne" },
  tochter: { meaning: "daughter", gender: "feminin", plural: "Töchter" },
  eltern: { meaning: "parents", gender: "neutral", plural: "Eltern" },
  mutter: { meaning: "mother", gender: "feminin", plural: "Mütter" },
  vater: { meaning: "father", gender: "maskulin", plural: "Väter" },
  bruder: { meaning: "brother", gender: "maskulin", plural: "Brüder" },
  schwester: { meaning: "sister", gender: "feminin", plural: "Schwestern" },
  familie: { meaning: "family", gender: "feminin", plural: "Familien" },
  freund: { meaning: "friend (male) / boyfriend", gender: "maskulin", plural: "Freunde" },
  freunde: { meaning: "friends", gender: "maskulin", plural: "Freunde" },
  freundin: { meaning: "friend (female) / girlfriend", gender: "feminin", plural: "Freundinnen" },
  mann: { meaning: "man / husband", gender: "maskulin", plural: "Männer" },
  lehrer: { meaning: "teacher", gender: "maskulin", plural: "Lehrer" },
  arzt: { meaning: "doctor / physician", gender: "maskulin", plural: "Ärzte" },
  student: { meaning: "student (university)", gender: "maskulin", plural: "Studenten" },

  // Time & calendar
  tag: { meaning: "day", gender: "maskulin", plural: "Tage" },
  tage: { meaning: "days", gender: "maskulin", plural: "Tage" },
  morgen: { meaning: "morning", gender: "maskulin" },
  abend: { meaning: "evening", gender: "maskulin", plural: "Abende" },
  nacht: { meaning: "night", gender: "feminin", plural: "Nächte" },
  jahr: { meaning: "year", gender: "neutral", plural: "Jahre" },
  jahre: { meaning: "years", gender: "neutral", plural: "Jahre" },
  jahren: { meaning: "years (dative plural)", gender: "neutral", plural: "Jahre" },
  woche: { meaning: "week", gender: "feminin", plural: "Wochen" },
  wochen: { meaning: "weeks", gender: "feminin", plural: "Wochen" },
  monat: { meaning: "month", gender: "maskulin", plural: "Monate" },
  monate: { meaning: "months", gender: "maskulin", plural: "Monate" },
  zeit: { meaning: "time", gender: "feminin" },
  uhr: { meaning: "clock / o'clock", gender: "feminin", plural: "Uhren" },
  stunde: { meaning: "hour", gender: "feminin", plural: "Stunden" },
  minute: { meaning: "minute", gender: "feminin", plural: "Minuten" },

  // Everyday things & food
  wasser: { meaning: "water", gender: "neutral" },
  brot: { meaning: "bread", gender: "neutral" },
  kaffee: { meaning: "coffee", gender: "maskulin" },
  tee: { meaning: "tea", gender: "maskulin" },
  milch: { meaning: "milk", gender: "feminin" },
  bier: { meaning: "beer", gender: "neutral" },
  wein: { meaning: "wine", gender: "maskulin" },
  apfel: { meaning: "apple", gender: "maskulin", plural: "Äpfel" },
  geld: { meaning: "money", gender: "neutral" },
  buch: { meaning: "book", gender: "neutral", plural: "Bücher" },
  bücher: { meaning: "books", gender: "neutral", plural: "Bücher" },
  auto: { meaning: "car", gender: "neutral", plural: "Autos" },
  autos: { meaning: "cars", gender: "neutral", plural: "Autos" },
  zug: { meaning: "train", gender: "maskulin", plural: "Züge" },
  bus: { meaning: "bus", gender: "maskulin", plural: "Busse" },
  fahrrad: { meaning: "bicycle / bike", gender: "neutral", plural: "Fahrräder" },
  haus: { meaning: "house / home", gender: "neutral", plural: "Häuser" },
  häuser: { meaning: "houses", gender: "neutral", plural: "Häuser" },
  wohnung: { meaning: "apartment / flat", gender: "feminin", plural: "Wohnungen" },
  zimmer: { meaning: "room", gender: "neutral", plural: "Zimmer" },
  tisch: { meaning: "table", gender: "maskulin", plural: "Tische" },
  stuhl: { meaning: "chair", gender: "maskulin", plural: "Stühle" },
  tür: { meaning: "door", gender: "feminin", plural: "Türen" },
  fenster: { meaning: "window", gender: "neutral", plural: "Fenster" },
  stadt: { meaning: "city / town", gender: "feminin", plural: "Städte" },
  land: { meaning: "country / rural land", gender: "neutral", plural: "Länder" },
  länder: { meaning: "countries", gender: "neutral", plural: "Länder" },
  weg: { meaning: "way / path", gender: "maskulin", plural: "Wege" },
  straße: { meaning: "street / road", gender: "feminin", plural: "Straßen" },
  arbeit: { meaning: "work / job", gender: "feminin" },
  beruf: { meaning: "profession / career", gender: "maskulin", plural: "Berufe" },
  schule: { meaning: "school", gender: "feminin", plural: "Schulen" },
  universität: { meaning: "university", gender: "feminin", plural: "Universitäten" },
  uni: { meaning: "university (colloquial)", gender: "feminin" },
  bahnhof: { meaning: "train station", gender: "maskulin", plural: "Bahnhöfe" },
  flughafen: { meaning: "airport", gender: "maskulin", plural: "Flughäfen" },
  hund: { meaning: "dog", gender: "maskulin", plural: "Hunde" },
  hunde: { meaning: "dogs", gender: "maskulin", plural: "Hunde" },
  katze: { meaning: "cat", gender: "feminin", plural: "Katzen" },
  katzen: { meaning: "cats", gender: "feminin", plural: "Katzen" },
  wetter: { meaning: "weather", gender: "neutral" },
  sonne: { meaning: "sun", gender: "feminin" },
  regen: { meaning: "rain", gender: "maskulin" },
  frage: { meaning: "question", gender: "feminin", plural: "Fragen" },
  fragen: { meaning: "questions / to ask", gender: "feminin", plural: "Fragen" },
  antwort: { meaning: "answer / reply", gender: "feminin", plural: "Antworten" },
  problem: { meaning: "problem", gender: "neutral", plural: "Probleme" },
  idee: { meaning: "idea", gender: "feminin", plural: "Ideen" },
  sprache: { meaning: "language", gender: "feminin", plural: "Sprachen" },
  deutsch: { meaning: "German (language)", gender: "neutral" },
  englisch: { meaning: "English (language)", gender: "neutral" },
  entscheidung: { meaning: "decision", gender: "feminin", plural: "Entscheidungen" },
  kauf: { meaning: "purchase / bargain", gender: "maskulin" },
  strömen: { meaning: "torrents / streams (dative plural)", gender: "maskulin" },
};

export const COMMON_ADJECTIVES_AND_ADVERBS: Record<string, { meaning: string; pos: string }> = {
  // Adjectives
  müde: { meaning: "tired", pos: "Adjektiv" },
  gut: { meaning: "good / well", pos: "Adjektiv / Adverb" },
  schlecht: { meaning: "bad / poorly", pos: "Adjektiv / Adverb" },
  schön: { meaning: "beautiful / nice", pos: "Adjektiv" },
  klein: { meaning: "small / little", pos: "Adjektiv" },
  kleinen: { meaning: "small (inflected)", pos: "Adjektiv" },
  groß: { meaning: "big / tall / great", pos: "Adjektiv" },
  großen: { meaning: "big (inflected)", pos: "Adjektiv" },
  alt: { meaning: "old", pos: "Adjektiv" },
  neu: { meaning: "new", pos: "Adjektiv" },
  jung: { meaning: "young", pos: "Adjektiv" },
  schnell: { meaning: "fast / quick", pos: "Adjektiv / Adverb" },
  langsam: { meaning: "slow / slowly", pos: "Adjektiv / Adverb" },
  warm: { meaning: "warm", pos: "Adjektiv" },
  kalt: { meaning: "cold", pos: "Adjektiv" },
  heiß: { meaning: "hot", pos: "Adjektiv" },
  früh: { meaning: "early", pos: "Adjektiv / Adverb" },
  spät: { meaning: "late", pos: "Adjektiv / Adverb" },
  teuer: { meaning: "expensive", pos: "Adjektiv" },
  billig: { meaning: "cheap", pos: "Adjektiv" },
  günstig: { meaning: "affordable / favorable", pos: "Adjektiv" },
  einfach: { meaning: "simple / easy / simply", pos: "Adjektiv / Adverb" },
  schwer: { meaning: "heavy / difficult", pos: "Adjektiv" },
  schwierig: { meaning: "difficult / challenging", pos: "Adjektiv" },
  wichtig: { meaning: "important", pos: "Adjektiv" },
  richtig: { meaning: "right / correct", pos: "Adjektiv / Adverb" },
  falsch: { meaning: "wrong / false", pos: "Adjektiv" },
  fertig: { meaning: "ready / finished", pos: "Adjektiv" },
  gesund: { meaning: "healthy", pos: "Adjektiv" },
  krank: { meaning: "sick / ill", pos: "Adjektiv" },
  klar: { meaning: "clear / evident", pos: "Adjektiv / Adverb" },
  toll: { meaning: "great / awesome", pos: "Adjektiv" },
  interessant: { meaning: "interesting", pos: "Adjektiv" },

  // Adverbs & particles
  heute: { meaning: "today", pos: "Temporaladverb" },
  morgen_adv: { meaning: "tomorrow", pos: "Temporaladverb" },
  gestern: { meaning: "yesterday", pos: "Temporaladverb" },
  jetzt: { meaning: "now", pos: "Temporaladverb" },
  immer: { meaning: "always", pos: "Temporaladverb" },
  nie: { meaning: "never", pos: "Temporaladverb" },
  niemals: { meaning: "never ever", pos: "Temporaladverb" },
  oft: { meaning: "often", pos: "Frequenzadverb" },
  manchmal: { meaning: "sometimes", pos: "Frequenzadverb" },
  schon: { meaning: "already", pos: "Fokuspartikel / Adverb" },
  noch: { meaning: "still / yet", pos: "Fokuspartikel / Adverb" },
  sehr: { meaning: "very", pos: "Gradadverb" },
  viel: { meaning: "much / a lot", pos: "Indefinitpronomen / Adverb" },
  viele: { meaning: "many", pos: "Indefinitpronomen" },
  wenig: { meaning: "little / few", pos: "Indefinitpronomen / Adverb" },
  gern: { meaning: "gladly / like to", pos: "Modaladverb" },
  gerne: { meaning: "gladly / like to", pos: "Modaladverb" },
  hier: { meaning: "here", pos: "Lokaladverb" },
  da: { meaning: "there / since", pos: "Lokaladverb / Konjunktion" },
  dort: { meaning: "there", pos: "Lokaladverb" },
  auch: { meaning: "also / too", pos: "Fokuspartikel" },
  nur: { meaning: "only", pos: "Fokuspartikel" },
  nicht: { meaning: "not", pos: "Negationspartikel" },
  kein: { meaning: "no / not a", pos: "Negationsartikel" },
  keine: { meaning: "no / not a (feminin/Plural)", pos: "Negationsartikel" },
  keinen: { meaning: "no / not a (maskulin Akkusativ)", pos: "Negationsartikel" },
  keinem: { meaning: "no / not a (Dativ)", pos: "Negationsartikel" },
  keiner: { meaning: "no / not a (feminin Dativ)", pos: "Negationsartikel" },
  ja: { meaning: "yes", pos: "Partikel" },
  nein: { meaning: "no", pos: "Partikel" },
  bitte: { meaning: "please / you're welcome", pos: "Höflichkeitspartikel" },
  vielleicht: { meaning: "maybe / perhaps", pos: "Modaladverb" },
  trotzdem: { meaning: "nevertheless / anyway", pos: "Konjunktionaladverb" },
  deshalb: { meaning: "therefore / that's why", pos: "Konjunktionaladverb" },
  deswegen: { meaning: "therefore / because of that", pos: "Konjunktionaladverb" },
  darum: { meaning: "therefore / that's why", pos: "Konjunktionaladverb" },
  sofort: { meaning: "immediately / right away", pos: "Temporaladverb" },
  bald: { meaning: "soon", pos: "Temporaladverb" },
  wieder: { meaning: "again", pos: "Temporaladverb" },
  zusammen: { meaning: "together", pos: "Modaladverb" },
  allein: { meaning: "alone", pos: "Modaladverb" },
  alleine: { meaning: "alone", pos: "Modaladverb" },
  leider: { meaning: "unfortunately", pos: "Modaladverb" },
  natürlich: { meaning: "of course / naturally", pos: "Modaladverb" },
  wirklich: { meaning: "really / truly", pos: "Gradadverb" },
  besonders: { meaning: "especially", pos: "Gradadverb" },
  ganz: { meaning: "quite / completely / whole", pos: "Gradadverb / Adjektiv" },
  etwas: { meaning: "something / somewhat", pos: "Indefinitpronomen" },
  nichts: { meaning: "nothing", pos: "Indefinitpronomen" },
  alles: { meaning: "everything / all", pos: "Indefinitpronomen" },
  alle: { meaning: "all / everyone", pos: "Indefinitpronomen" },
  jemand: { meaning: "someone", pos: "Indefinitpronomen" },
  niemand: { meaning: "no one / nobody", pos: "Indefinitpronomen" },
};

export const COMMON_NAMES_AND_PLACES: Record<string, { meaning: string; pos: string }> = {
  becker: { meaning: "Becker (surname)", pos: "Eigenname (Nachname)" },
  müller: { meaning: "Müller (surname)", pos: "Eigenname (Nachname)" },
  schmidt: { meaning: "Schmidt (surname)", pos: "Eigenname (Nachname)" },
  schneider: { meaning: "Schneider (surname)", pos: "Eigenname (Nachname)" },
  fischer: { meaning: "Fischer (surname)", pos: "Eigenname (Nachname)" },
  weber: { meaning: "Weber (surname)", pos: "Eigenname (Nachname)" },
  meyer: { meaning: "Meyer (surname)", pos: "Eigenname (Nachname)" },
  wagner: { meaning: "Wagner (surname)", pos: "Eigenname (Nachname)" },
  schulz: { meaning: "Schulz (surname)", pos: "Eigenname (Nachname)" },

  anna: { meaning: "Anna (given name)", pos: "Eigenname (Vorname)" },
  lucas: { meaning: "Lucas (given name)", pos: "Eigenname (Vorname)" },
  lukas: { meaning: "Lukas (given name)", pos: "Eigenname (Vorname)" },
  michael: { meaning: "Michael (given name)", pos: "Eigenname (Vorname)" },
  maria: { meaning: "Maria (given name)", pos: "Eigenname (Vorname)" },
  thomas: { meaning: "Thomas (given name)", pos: "Eigenname (Vorname)" },
  stefan: { meaning: "Stefan (given name)", pos: "Eigenname (Vorname)" },
  julia: { meaning: "Julia (given name)", pos: "Eigenname (Vorname)" },
  max: { meaning: "Max (given name)", pos: "Eigenname (Vorname)" },
  felix: { meaning: "Felix (given name)", pos: "Eigenname (Vorname)" },
  lisa: { meaning: "Lisa (given name)", pos: "Eigenname (Vorname)" },
  jan: { meaning: "Jan (given name)", pos: "Eigenname (Vorname)" },
  sarah: { meaning: "Sarah (given name)", pos: "Eigenname (Vorname)" },
  paul: { meaning: "Paul (given name)", pos: "Eigenname (Vorname)" },

  österreich: { meaning: "Austria", pos: "Eigenname (Land / Toponym)" },
  deutschland: { meaning: "Germany", pos: "Eigenname (Land / Toponym)" },
  schweiz: { meaning: "Switzerland", pos: "Eigenname (Land / Toponym)" },
  berlin: { meaning: "Berlin (capital of Germany)", pos: "Eigenname (Stadt / Toponym)" },
  wien: { meaning: "Vienna (capital of Austria)", pos: "Eigenname (Stadt / Toponym)" },
  zürich: { meaning: "Zurich (city in Switzerland)", pos: "Eigenname (Stadt / Toponym)" },
  münchen: { meaning: "Munich (city in Germany)", pos: "Eigenname (Stadt / Toponym)" },
  hamburg: { meaning: "Hamburg (city in Germany)", pos: "Eigenname (Stadt / Toponym)" },
  köln: { meaning: "Cologne (city in Germany)", pos: "Eigenname (Stadt / Toponym)" },
  frankfurt: { meaning: "Frankfurt (city in Germany)", pos: "Eigenname (Stadt / Toponym)" },
};

export const COLLOCATIONS = [
  {
    pattern: /entscheidung\s+getroffen|entscheidung\s+treffen/i,
    nounPhrase: "eine Entscheidung",
    verb: "treffen",
    meaning: "to make a decision",
    literal: "to strike a decision",
    explanation: "German uses 'eine Entscheidung treffen' where English says 'make a decision' (never *'eine Entscheidung machen').",
  },
  {
    pattern: /in\s+frage\s+stellen|in\s+frage\s+stellt/i,
    nounPhrase: "in Frage",
    verb: "stellen",
    meaning: "to call into question",
    literal: "to place into question",
    explanation: "Academic and formal collocation: 'in Frage stellen' means to doubt or scrutinize validity.",
  },
  {
    pattern: /zur\s+sprache\s+gebracht|zur\s+sprache\s+bringen/i,
    nounPhrase: "zur Sprache",
    verb: "bringen",
    meaning: "to bring up for discussion",
    literal: "to bring to language",
    explanation: "High-register noun-verb combination meaning to table a topic in a formal discussion.",
  },
  {
    pattern: /in\s+kauf\s+nehmen|in\s+kauf\s+genommen/i,
    nounPhrase: "in Kauf",
    verb: "nehmen",
    meaning: "to accept a drawback / put up with",
    literal: "to take into purchase",
    explanation: "Fixed business and everyday collocation meaning to knowingly accept a disadvantage.",
  },
  {
    pattern: /abschied\s+nehmen|abschied\s+genommen/i,
    nounPhrase: "Abschied",
    verb: "nehmen",
    meaning: "to say goodbye / take leave",
    literal: "to take farewell",
    explanation: "Formal collocation for parting ('von jdm. Abschied nehmen').",
  },
  {
    pattern: /zur\s+verf[uü]gung\s+stellen|zur\s+verf[uü]gung\s+stehen/i,
    nounPhrase: "zur Verfügung",
    verb: "stellen / stehen",
    meaning: "to make available / to be available",
    literal: "to place / stand at disposal",
    explanation: "Widely used active ('stellen') and passive ('stehen') professional collocations.",
  },
  {
    pattern: /in\s+betracht\s+ziehen|in\s+erw[aä]gung\s+ziehen/i,
    nounPhrase: "in Betracht / Erwägung",
    verb: "ziehen",
    meaning: "to consider / take into account",
    literal: "to pull into consideration",
    explanation: "Advanced administrative collocation used for weighing alternatives.",
  },
  {
    pattern: /in\s+str[oö]men\s+regnen|in\s+str[oö]men\s+regnete/i,
    nounPhrase: "in Strömen",
    verb: "regnen",
    meaning: "to pour rain / rain heavily",
    literal: "to rain in torrents",
    explanation: "Idiomatic weather expression pairing plural dative 'Strömen' with 'regnen'.",
  },
];
